Add search index method functionality
LangeHenrik/SDU-SE-F22 pull request #123
Opened 2022-03-22 14:37 UTC by ComradeTA

2022-03-22 14:46 UTC, OthelloEngineer commented on src/main/java/dk/sdu/se_f22/brandmodule/index/BrandIndex.java
> +            ResultSet
ResultSet???

2022-03-22 14:51 UTC, OthelloEngineer requested changes
You're making a format for a query,
trying an SQLquery,
preparing a statement,
preparing another nested statement, 
executing the statement, and
formatting your ResultSet.

Use method extraction and consider calling the same extracted method when preparing your second statement. 

“In order to make sure our functions are doing 'one thing', we need to make sure that the statements within the function are all at the same level of abstraction.” - Uncle Bob (Clean code)

2022-03-25 00:20 UTC, mathiasgredal requested changes
You have to close prepared statements and result sets. This is preferably done using try-with-resources.

2022-03-25 00:20 UTC, mathiasgredal commented on src/main/java/dk/sdu/se_f22/brandmodule/index/BrandIndex.java
> +                PreparedStatement queryStatement = DBConn.prepareStatement("SELECT id FROM Tokens WHERE token = ?");
Prepared statement is never closed

2022-03-25 00:20 UTC, mathiasgredal commented on src/main/java/dk/sdu/se_f22/brandmodule/index/BrandIndex.java
> +                ResultSet queryResultSet = queryStatement.executeQuery();
Resultset is never closed

2022-03-25 00:20 UTC, mathiasgredal commented on src/main/java/dk/sdu/se_f22/brandmodule/index/BrandIndex.java
> +            PreparedStatement queryStatement = DBConn.prepareStatement(finalQuery);
This prepared statement is not closed either

2022-03-25 00:20 UTC, mathiasgredal commented on src/main/java/dk/sdu/se_f22/brandmodule/index/BrandIndex.java
> +            ResultSet queryResultSet = queryStatement.executeQuery();
This resultset is not closed

2022-04-26 09:35 UTC, merged