Som 2
LangeHenrik/SDU-SE-F22 pull request #139
Opened 2022-03-29 11:01 UTC by LaugeSolvang

2022-03-29 11:10 UTC, MGertz requested changes
Be aware some files isnt going into the correct folders.
Make sure to use folder sortingmodule/scoring/...

2022-03-29 11:16 UTC, The0mikkel commented on src/main/java/dk/sdu/se_f22/som2/IScoring.java
> +package dk.sdu.se_f22.som2;
This file should not be located here?!
Please insert all of your codes into sortingmodule/scoring

2022-03-29 11:17 UTC, The0mikkel commented on src/main/java/dk/sdu/se_f22/som2/Scoring.java
> +package dk.sdu.se_f22.som2;
The same is applicable here

2022-03-29 11:20 UTC, The0mikkel requested changes
Please move all of your code into `sortingmodule/scoring/...`, so that any code is present, in the correct location and not floating around.

2022-03-29 11:20 UTC, The0mikkel commented on src/main/java/dk/sdu/se_f22/som2/Test.java
> +package dk.sdu.se_f22.som2;
The same is applicable here.

2022-04-05 12:10 UTC, The0mikkel commented on src/main/java/dk/sdu/se_f22/sortingmodule/scoring/Scoring.java
> +            connection = DriverManager.getConnection("jdbc:postgresql://" + url + ":" + port + "/" + databaseName, username, password);
I would like you to use the common database connection, with is provided in the "DBConnection" -> `DBConnection.getPooledConnection();`
Then follow the readme in the main repository branch, where it says on how to configure this connection (through "config.properties"

2022-04-05 12:15 UTC, The0mikkel commented
I'm not quite sure, how we, as the infrastructure in the SOM module, should use your system?
Is ant of this code made for us to use, or is it part of the crud?

We would very much just like to send the whole "SearchHits" object to you guys, where from here, you just sort in that, or how was it though on your side?

Please see my commect regarding database connection. With your current setup, we would not be able to use your code.

2022-04-05 12:16 UTC, The0mikkel requested changes

2022-04-05 12:16 UTC, The0mikkel commented on src/main/java/dk/sdu/se_f22/sortingmodule/scoring/Scoring.java
> +            connection = DriverManager.getConnection("jdbc:postgresql://" + url + ":" + port + "/" + databaseName, username, password);
I would like you to use the common database connection, with is provided in the "DBConnection" -> `DBConnection.getPooledConnection();`
Then follow the readme in the main repository branch, where it says on how to configure this connection (through "config.properties"

2022-04-26 14:37 UTC, merged