Added a Admin search GUI and tests
LangeHenrik/SDU-SE-F22 pull request #253
Opened 2022-05-24 08:26 UTC by Darchie4

2022-05-24 08:28 UTC, mathiasgredal approved these changes
Looks good to me

2022-05-24 11:25 UTC, marc7636 commented
The bug causing the NullReferenceExceptions has been fixed on the main branch

2022-05-24 12:48 UTC, marc7636 requested changes
Please pull the latest main commit before it breaks again

2022-05-24 13:42 UTC, marc7636 approved these changes

2022-05-28 06:59 UTC, jakob753951 commented
Jeg kan se at der er ændret i gruppe 3.1s kode, er det noget de har lavet selv, eller har de givet approval?

2022-05-28 09:21 UTC, mathiasgredal commented
> Jeg kan se at der er ændret i gruppe 3.1s kode, er det noget de har lavet selv, eller har de givet approval?

Har tilføjet dem som reviewers.

2025-02-07 15:14 UTC, closed without merging