Merging in to main from our branch
LangeHenrik/SDU-SE-F22 pull request #264
Opened 2022-05-24 12:39 UTC by zackaad

We corrected the failing test. :-D

2022-05-24 12:46 UTC, marc7636 approved these changes
Looking good :)

2022-05-24 12:47 UTC, MagnusHJensen approved these changes
LGTM

2022-05-24 13:28 UTC, mathiasgredal requested changes

2022-05-25 11:24 UTC, zackaad commented on src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/Search/IsearchIndexedHTML.java
> +public interface IsearchIndexedHTML {
Hvorfor vil du have at interfacet arver IndexingModule? :)

2022-05-26 23:24 UTC, mathiasgredal commented on src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/Search/IsearchIndexedHTML.java
> +public interface IsearchIndexedHTML {
Pga. dependency inversion, og fordi brand index og product index begge gør det samme.

2022-05-27 10:04 UTC, mathiasgredal requested changes

2022-05-27 10:04 UTC, mathiasgredal commented on src/main/java/dk/sdu/se_f22/contentmodule/infrastructure/domain/Search/SearchClass.java
> +            return null;
Kan det her være en tom liste i stedet?

2023-02-23 13:04 UTC, merged

2023-02-23 17:07 UTC, MagnusHJensen commented
Damn man @Autowinto